apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stats
spec:
  selector:
    matchLabels:
      name: stats-pods
  template:
    metadata:
      labels:
        name: stats-pods
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      terminationGracePeriodSeconds: 0
      containers:
        - name: stats
          image: busybox
          securityContext:
            # Run a priv container so we really do measure what is happening on the
            # host (node) system
            privileged: true
          command:
              - "tail"
              - "-f"
              - "/dev/null"
          stdin: true
          tty: true
