# This is a temporary reference commit until a working prometheus for 1.16 is released
# (dashboard-deployment api version not updated in v0.2.0, breaking k8s 1.16)
# f458e85e5d7675f7bc253072e1b4c8892b51af0f
resources:
  - kube-prometheus/manifests/00namespace-namespace.yaml
  - kube-prometheus/manifests/0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  - kube-prometheus/manifests/0prometheus-operator-0prometheusCustomResourceDefinition.yaml
  - kube-prometheus/manifests/0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  - kube-prometheus/manifests/0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
  - kube-prometheus/manifests/0prometheus-operator-clusterRoleBinding.yaml
  - kube-prometheus/manifests/0prometheus-operator-clusterRole.yaml
  - kube-prometheus/manifests/0prometheus-operator-deployment.yaml
  - kube-prometheus/manifests/0prometheus-operator-serviceAccount.yaml
  - kube-prometheus/manifests/0prometheus-operator-serviceMonitor.yaml
  - kube-prometheus/manifests/0prometheus-operator-service.yaml
  - kube-prometheus/manifests/alertmanager-alertmanager.yaml
  - kube-prometheus/manifests/alertmanager-secret.yaml
  - kube-prometheus/manifests/alertmanager-serviceAccount.yaml
  - kube-prometheus/manifests/alertmanager-serviceMonitor.yaml
  - kube-prometheus/manifests/alertmanager-service.yaml
  - kube-prometheus/manifests/grafana-dashboardDatasources.yaml
  - kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
  - kube-prometheus/manifests/grafana-dashboardSources.yaml
  - kube-prometheus/manifests/grafana-deployment.yaml
  - kube-prometheus/manifests/grafana-serviceAccount.yaml
  - kube-prometheus/manifests/grafana-serviceMonitor.yaml
  - kube-prometheus/manifests/grafana-service.yaml
  - kube-prometheus/manifests/kube-state-metrics-clusterRoleBinding.yaml
  - kube-prometheus/manifests/kube-state-metrics-clusterRole.yaml
  - kube-prometheus/manifests/kube-state-metrics-deployment.yaml
  - kube-prometheus/manifests/kube-state-metrics-roleBinding.yaml
  - kube-prometheus/manifests/kube-state-metrics-role.yaml
  - kube-prometheus/manifests/kube-state-metrics-serviceAccount.yaml
  - kube-prometheus/manifests/kube-state-metrics-serviceMonitor.yaml
  - kube-prometheus/manifests/kube-state-metrics-service.yaml
  - kube-prometheus/manifests/node-exporter-clusterRoleBinding.yaml
  - kube-prometheus/manifests/node-exporter-clusterRole.yaml
  - kube-prometheus/manifests/node-exporter-daemonset.yaml
  - kube-prometheus/manifests/node-exporter-serviceAccount.yaml
  - kube-prometheus/manifests/node-exporter-serviceMonitor.yaml
  - kube-prometheus/manifests/node-exporter-service.yaml
  - kube-prometheus/manifests/prometheus-adapter-apiService.yaml
  - kube-prometheus/manifests/prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - kube-prometheus/manifests/prometheus-adapter-clusterRoleBindingDelegator.yaml
  - kube-prometheus/manifests/prometheus-adapter-clusterRoleBinding.yaml
  - kube-prometheus/manifests/prometheus-adapter-clusterRoleServerResources.yaml
  - kube-prometheus/manifests/prometheus-adapter-clusterRole.yaml
  - kube-prometheus/manifests/prometheus-adapter-configMap.yaml
  - kube-prometheus/manifests/prometheus-adapter-deployment.yaml
  - kube-prometheus/manifests/prometheus-adapter-roleBindingAuthReader.yaml
  - kube-prometheus/manifests/prometheus-adapter-serviceAccount.yaml
  - kube-prometheus/manifests/prometheus-adapter-service.yaml
  - kube-prometheus/manifests/prometheus-clusterRoleBinding.yaml
  - kube-prometheus/manifests/prometheus-clusterRole.yaml
  - kube-prometheus/manifests/prometheus-prometheus.yaml
  - kube-prometheus/manifests/prometheus-roleBindingConfig.yaml
  - kube-prometheus/manifests/prometheus-roleBindingSpecificNamespaces.yaml
  - kube-prometheus/manifests/prometheus-roleConfig.yaml
  - kube-prometheus/manifests/prometheus-roleSpecificNamespaces.yaml
  - kube-prometheus/manifests/prometheus-rules.yaml
  - kube-prometheus/manifests/prometheus-serviceAccount.yaml
  - kube-prometheus/manifests/prometheus-serviceMonitorApiserver.yaml
  - kube-prometheus/manifests/prometheus-serviceMonitorCoreDNS.yaml
  - kube-prometheus/manifests/prometheus-serviceMonitorKubeControllerManager.yaml
  - kube-prometheus/manifests/prometheus-serviceMonitorKubelet.yaml
  - kube-prometheus/manifests/prometheus-serviceMonitorKubeScheduler.yaml
  - kube-prometheus/manifests/prometheus-serviceMonitor.yaml
  - kube-prometheus/manifests/prometheus-service.yaml
