bases:
- ../base/
patchesJson6902:
# increase limits in kubelet
- target:
    group: kubelet.config.k8s.io
    version: v1beta1
    kind: KubeletConfiguration
    name: kubelet-config
  path: kubelet-config.json
# increase the address range per node
- target:
    group: kubeadm.k8s.io
    version: v1beta1
    kind: ClusterConfiguration
    name: cluster-config
  path: cluster-config.json
