# If you set "deviceType": "vfio",
# - uncomment line `bind_vfs_vfio $pf` in systemd/sriov.sh
# - set "type": "vfioveth" in test/sriov/0-sriov-net.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sriov-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList":
      [
        {
          "resourceName": "sriov",
          "rootDevices": ["07:00.0", "07:00.1"],
          "sriovMode": true,
          "deviceType": "netdevice"
        }
      ]
    }
