apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  mon:
    allowMultiplePerNode: true
    count: 1
  storage:
    directories:
     - path: /var/lib/rook
